### ISSUE TITLE
Run tests only locally?

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#2]
For this package, I suggest using comprehensive tests to check the function with the many different modelling packages. However, this would require adding those packages to `SUGGEST`, which foils our approach to keep dependencies at a minimum.

Should we add `tests` to Rbuildignore, so tests are only run locally, but not on CRAN?

**Comment by strengejacke** [comment]
@DominiqueMakowski maybe I need to ping you?!?

**Comment by DominiqueMakowski** [comment]
I get notified with by mail for every new activity, so it's mostly just a matter of jet lag (+7h here in Asia) 😄 

Hum, this is indeed a concern. On the one hand, I really like having the testing suite checked by travis, CRAN, codecov and such. It helps getting notified when something breaks due to updates in other dependencies (in our case, due to changes to the packages related to the models). On the other hand, this would indeed require adding all those packages to SUGGEST.

I believe for the end-user it doesn't matter since (correct me if I'm wrong) when he's downloading the package it only imports the IMPORT packages. However, it does matter for travis and CRAN and the people that want to contribute, test it and so on. 

I would not be against adding the packages to SUGGEST and see how it does (I have in mind the example of broom that has very few IMPORTs, but naturally has lots of SUGGESTs), but I understand that it might be a concern. One of the trade-offs could be to have a Rda file stored here on github, that the testing suite would download, that stores different already-fitted models. However, I'm not sure it would work and moreover this approach would not be sensitive to any updates in the models fitting packages. So probably not a good solution.

Maybe we could start by setting up a testing suite including the base models (lm glm) and then, for the external ones, either we leave them as comments (to run locally) or can try adding them to suggests and see. As I'm writing this, I reckon we might, in the end, still need these packages in SUGGEST in order to write vignettes with examples and tutorials...

**Comment by strengejacke** [comment]
True, suggested packages should not be installed, even not with `dependencies = TRUE`, I think. So we don't need to skip tests on CRAN.

I still would suggest using a trick I learned from Dirk Eddenbuettel, I think. Some tests that are time consuming should only run locally, as this is asked by CRAN. So for Stan-Models, I would add a conditional if-statement that checks if the package-version is a developer version, and only runs tests then.

**Comment by DominiqueMakowski** [comment]
Yes absolutely, in psycho I had some problems with stan models that led to turning off test-checks on CRAN, so I'm glad to have learnt that trick :)

**Comment by DominiqueMakowski** [comment]
I published the dev branch, we can start committing to it to keep it ahead and merging to master from time to time (I suggest we do not start increasing the version yet before having a first running prototype)
