### ISSUE TITLE
find_ and get_parameters

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#24]
Re-writing some code in bayestestR, I realised it would be quite convenient to have another consistent stable extraction function, related to the parameters:

```r
find_parameters <- function(model) {
  return(names(coef(model)))
}

get_parameters <- function(model) {
  return(as.data.frame(model)[find_parameters(model)])
}
```

For Bayesian models, it would return the posterior of the model's parameters. However, for frequentist models, I am still unsure whether it should return only the betas or other metrics (such as SE). I am leaning toward the first option.

One of the purposes of this function would be to unify the different `coef`, `fixef` options that work differently (or does not work at all) depending on the model. For instance brms errors when using `coef` in favour of `fixef`. However, using it need in turn importing packages (brmsn or lme4), which we would like to avoid...

PS: Also, side question, what are the reasons to remove the explicit `return()` at the end of functions?

**Comment by strengejacke** [comment]
The missing return is just a code style question. I think this is an R style, and recommended here:
http://adv-r.had.co.nz/Functions.html#return-values
In the end, it's just a matter of taste.

**Comment by strengejacke** [comment]
I think this is a good idea, although it would strongly overlap with broom and broom.mixed. but I have my own tidiers anyway, so it might be good to have a light weight implementation.

We should put this on the list for the update after initial submission, because especially for more complex / Bayesian models there are many things to consider.

**Comment by strengejacke** [comment]
Maybe, if we only wrap `coef()`, it might be easier to do. The hard work comes when we want to clean names.

**Comment by DominiqueMakowski** [comment]
Although I was not necessarily thinking about returning all the parameters info (as broom and broom.mixed), just the minimal values related to parameters (point-estimates / posteriors)

However, I am still thinking that our own solution for a nicely formatted table for parameters, more complete than broom, would be very useful indeed... but probably had its place in a separate package

**Comment by strengejacke** [comment]
For Bayesian models, we need to think about reformatting the parameter names, or if we want to keep them as they are (including `b_` and such stuff).

**Comment by DominiqueMakowski** [comment]
Hum, I think that a bit of reformatting is gonna be necessary. That would also provide a superiority compared to broom. 

Would it work through some fuzzy string matching between find_predictors names and the parameters as returned by coef/fixed and so on?

**Comment by strengejacke** [comment]
There's a pattern for parameter naming in brms. Here's a quote from Paul, who explains this:

The formal definition of the main parameter classes is as follows:

constant effect: `b_<term>`
varying effect: `r_<group>__<parameter>_<response>[<level>,<predictor>]`
SD of varying effects: `sd_<group>__<term>`
Cor of varying effects: `cor_<group>__<term>__<term>`
non-predicted distributional parameter: `<parameter>_<response>`

In all of the above, `<terms>` may have up to 3 components: `<parameter>_<response>_<predictor>`,
where `<response>` is generally suppressed if the model is univariate and `<parameter>` is generally suppressed if the main parameter `mu` is predicted (instead of `zi`, `sigma` or whatever).

The double underscores appear behind `<group>` and `<predictor>` if there is something else that follows to disambiguate the names as `<group>` and `<predictor` may contain underscores but not double underscores or underscores at the end. Both `<parameter>` and `<response>` may not contain any underscores and thus don't need double underscores.

The definition of the varying effects is not perfectly consistent, as it would perhaps have been better to
name them `r_<group>[<level>,<term>]`, but I guess it's too late for that.

**Comment by strengejacke** [comment]
If you look at the code from `tidy_stan()` (https://github.com/strengejacke/sjstats/blob/master/R/tidy_stan.R), you see the challange for such "cleaning" functions ;-)

There is an (slightly outdated) example: http://rpubs.com/sjPlot/tidy_stan

This is of course not what we want to do, but I would expect that a function that returns (posterior draws of) parameters, also gives me the "original" parameter names (like in `coef()`). So we have to do some regex-stuff, I think, but for `find_*()` and `get_parameters()` we should keep it simple, focussing on fixed effects (but even this becomes complicated for multivariate response and / or zero-inflated models etc.).

**Comment by DominiqueMakowski** [comment]
Agree, we can always expand it later if there is ever such a need with some `part="random"` parameter

**Comment by strengejacke** [comment]
You're right, it wouldn't make sense for a function that returns parameters only to focus on fixed effects.

**Comment by strengejacke** [comment]
I _hate_ regex and will _never_ understand them... But anyway, I think I have found a solution for brms.

**Comment by DominiqueMakowski** [comment]
thanks a lot 🥇 for struggling with this tremendously unintuitive stuff

**Comment by strengejacke** [comment]
What do you say?
http://rpubs.com/sjPlot/insight-get_parameters

**Comment by strengejacke** [comment]
- Should we move this function into the parameters-package?
- Do you think the design of the function is OK?
- We need to add rstanarm support
- We need to add MixMod support

I guess there are some model objects that won't work due to the lack of a `coef()`-function, but we can add that later... The main purpose is to support Baysian models anyway.

**Comment by strengejacke** [comment]
Ok, stanreg-support is added... If I haven't missed anything, zero-inflated is not yet supported by rstanarm?

**Comment by DominiqueMakowski** [comment]
My feeling is to keep the function here. The function design seems great, we'll see how it stands the test of usage :)
