### ISSUE TITLE
Prepare for more exporting: alias for format_table?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#248]
Related to https://github.com/easystats/correlation/issues/109

Currently format_table() is used to transform a data.frame into a string-like output that gets nicely printed in the console. Though this is sometimes a bit confusing as we also have `format_parameters()` etc., maybe we could add a more explicit name for it?

For instance, `export_to_console()` so that we could see in the future `export_to_latex()` etc. And we know that this function doesn't do any formatting (I mean, it does, but not in that sense, it does not really change the content, it mostly adapts it to a given output). 

What do you think?

**Comment by strengejacke** [comment]
I have added a `style`-argument (maybe we can rename it to `format`?), that allows for different output formats (to be implemented). It currently works for markdown, so we may have automatic table printing inside markdown documents using `knitr_print()`.

``` r
data(iris)
iris$Petlen <- cut(iris$Petal.Length, breaks = c(0, 3, 7))
model <- lm(Sepal.Width ~ poly(Sepal.Length, 2) + Species + Petlen, data = iris)

library(parameters)
library(magrittr)
mp <- model_parameters(model)
mp %>% 
  parameters_table() %>% 
  insight::format_table(mp, style = "markdown")
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">95% CI</th>
<th style="text-align: right;">t(144)</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.81</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">[ 3.70, 3.93]</td>
<td style="text-align: right;">65.50</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Length [1st degree]</td>
<td style="text-align: right;">4.06</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">[ 3.14, 4.98]</td>
<td style="text-align: right;">8.70</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sepal.Length [2nd degree]</td>
<td style="text-align: right;">-1.30</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">[-1.92, -0.68]</td>
<td style="text-align: right;">-4.14</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Species [versicolor]</td>
<td style="text-align: right;">-1.01</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">[-1.56, -0.46]</td>
<td style="text-align: right;">-3.62</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Species [virginica]</td>
<td style="text-align: right;">-0.99</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">[-1.55, -0.43]</td>
<td style="text-align: right;">-3.48</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Petlen [4-7]</td>
<td style="text-align: right;">-0.14</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">[-0.69, 0.42]</td>
<td style="text-align: right;">-0.48</td>
<td style="text-align: right;">0.630</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
https://stackoverflow.com/a/63176315/2094622 (reminder for subheadings)

**Comment by strengejacke** [comment]
I don't quite understand it, when is `knit_print()` called within an rmarkdown file and when not?

I added a method 

```r
#' @export
knit_print.parameters_model <- function(x, ...) {
# ...
}
```

But nothing happens when I use this code in rmarkdown:

```r
data(iris)
iris$Petlen <- cut(iris$Petal.Length, breaks = c(0, 3, 7))
model <- lm(Sepal.Width ~ poly(Sepal.Length, 2) + Species + Petlen, data = iris)

model_parameters(model)
```

**Comment by strengejacke** [comment]
We may have a generic `to_table()` in _insight_, with class-specific methods in the related packages, what do you think? I think `export` sounds to much like exporting data into a file.

**Comment by strengejacke** [comment]
My suggestion:

- we have a generic [`to_table()`](https://easystats.github.io/insight/reference/to_table.html) in _insight_ that can be re-exported and adapted as needed in our packages. For example, in _parameters, we have a [`to_table.parameters_model()`](https://github.com/easystats/parameters/blob/master/R/to_table.R), which basically copies the normal `print.parameters_models()`] with some minor adaptions required for markdown.

- in _insight_, I have revised [`format_table()`](https://easystats.github.io/insight/reference/format_table.html) and added some options for markdown-tables. These additional features should be used in `to_table()`. The current implementation does not break any code, it's just a "surplus" on top of the existing functionality.

- since CI's look better with parentheses in HTML/Word/PDF, I changed the functioning of the `brackets`-argument in [`format_ci()`](https://easystats.github.io/insight/reference/format_ci.html). It can now also be a length-2 character vector with own bracket-strings, like `brackets = c("(", ")")`.

Now, the code in a markdown document may look like this:

```r
data(iris)
iris$Petlen <- cut(iris$Petal.Length, breaks = c(0, 3, 7))
model <- lm(Sepal.Width ~ poly(Sepal.Length, 2) + Species + Petlen, data = iris)

model_parameters(model) %>% 
  to_table()


library(glmmTMB)
data("fish")

model <- glmmTMB(
  count ~ child + camper + (1 | persons),
  ziformula = ~ child + camper + (1 | persons),
  data = fish,
  family = truncated_poisson()
)

model_parameters(model) %>% 
  to_table()
```

## When this rmarkdown is knit to HTML

![image](https://user-images.githubusercontent.com/26301769/99390238-98690b00-28d8-11eb-946a-32d118a6224e.png)

## When this rmarkdown is knit to PDF

![image](https://user-images.githubusercontent.com/26301769/99390321-b8003380-28d8-11eb-9d95-05f696a36c82.png)

## When this rmarkdown is knit to Word

![image](https://user-images.githubusercontent.com/26301769/99390408-e251f100-28d8-11eb-8776-f80e432b8313.png)


So, it all depends on the related individual `print()`-methods in each package, for each function. Basically, `to_table()` can copy the code from `print()`, just the call to `insight::format_table()` should include the argument `format = "markdown"`. This _may_ be extended to LaTex in the future...

**Comment by strengejacke** [comment]
> Though this is sometimes a bit confusing as we also have format_parameters() etc.,

I have prepared a [vignette](https://github.com/easystats/parameters/blob/master/vignettes/model_parameters_formatting.Rmd) on this topic, which maybe reduces the confusion a bit.

**Comment by DominiqueMakowski** [comment]
let me read the vignette (how come it didn't got build on the website :think)

**Comment by DominiqueMakowski** [comment]
so If I summarize, we have a new `to_table` method that does `parameters_table()` + `format_table(format = "markdown")` that we need to add to new objects. But what for objects that don't go through `parameters_table()` (tho I can't think of any)?

**Comment by DominiqueMakowski** [comment]
Though I wonder if `to_table()` isn't to "vague" somehow. Maybe we should alias it as `table_to_markdown()` (or `table_to_md`, html or latex), because we could foresee also maybe some `text_to_markdown()` that could be maybe used for the text of reports to nicely print like bold, italic and all, no?

**Comment by strengejacke** [comment]
> let me read the vignette (how come it didn't got build on the website :think)

It requires insight from CRAN, due to the `to_table()` generic.

**Comment by strengejacke** [comment]
> so If I summarize, we have a new to_table method that does parameters_table() + format_table(format = "markdown") that we need to add to new objects. But what for objects that don't go through parameters_table() (tho I can't think of any)?

Well, `to_table()` is quite flexible, it is not forced to rely on parameters_table() + format_table(format = "markdown"). But currently, it is used in this way in _parameters_ and in the implementation in _correlation_, mainly because `format_table()` creates this table as character vector(s), which we also need for markdown tables.

But yes, we can also add an alias to it. You may also add a `format`-argument to `to_table()`, to allow the creation of html/latex/markdown tables, so it's _very_ flexible.

**Comment by strengejacke** [comment]
See also the code for [`correlation::to_table.R`](https://github.com/easystats/correlation/blob/master/R/to_table.R) - it's really just a `print()` method, that returns a different string for the table-layout, so it generates valid markdown tables (and it adds the knitr-class-attribute, so it gets recognized inside rmarkdown docs).

**Comment by DominiqueMakowski** [comment]
The only thing I have isthat for instance this chunk 

https://github.com/easystats/correlation/blob/2b4a2084006a309177561cbaabf370621178c941/R/to_table.R#L47-L58

should be common across the printing to console (i.e., the regular print() method) and to MD format. Meaning that the preprocessing should be done before hand, and both `print()` and "print-to-md" (which are as u say conceptually two modes of printing methods) should just transform the "prepared" dataframe input to a given format (a string that gets `cat` in print or a md/latex like string).


So I think we need to have a clear idea of the overall hierarchy of functions. Here's a possibility:

First of all, I conceptualize the base `print()` method as an alias for `print_to_console()`.

We start with a complex object from easystats, that has attributes and all.
- If it goes directly to `print()` (i.e., `print_to_console()`, i.e., gets displayed in the console), it runs:
  - `parameters_table()`: transforms the raw dataframe into the end dataframe with good names and all
  - `export_to_console()`: formats it for the console
- Else, one can `print_to_md()`, which runs:
  - `parameters_table()`: same as above
  - export_to_md(): formats it for md
- Else, users can just run `parameters_table()` and do as they like with the "clean" data.frame (further modify it or such)

So now the only API-issue is that we tend to use `parameters_table` for pretty much everything, but I wonder if we should make it more general, like rename it to `format_table()` (so unlike the current design you mentioned above, format_tables still returns a dataframe, but a "clean" dataframe. And the "output-driven" output is transformed by exporting functions). What do you think of a structure like this?

**Comment by strengejacke** [comment]
I understand your point. I think it is difficult to have a clear distinction between `format_table()` (i.e. the former `parameters_table()`) and `export_table()` or such (i.e. the former `format_table()`). Both functions are actually doing some "formatting" (one formats pretty numbers/column names, the other formats the string into plain text/md/...). But maybe indeed `parameters_table()` can become `format_table()`, however, we must first rename `format_table()` into something else.

I'd vote for `export_table()`, with a `format` argument, and then methods like `print_to_md()` call `export_table(format = "md")` etc.

**Comment by strengejacke** [comment]
But still I like the `to_table()`, because it is quite clear what it does: it converts the output of functions (which go as "text comment" by default in markdown docs) into a proper table. So there's nothing wrong with that name? @IndrajeetPatil any opinion?

**Comment by strengejacke** [comment]
> And the "output-driven" output is transformed by exporting functions). What do you think of a structure like this?

We can do this to some extent, but still we have much "edge cases" that are handled inside the `print()` methods. I have revised `export_table()` (former `format_table()`), so you can now also pass a caption and footer (both including colors) for plain text tables. See, for instance, `performance::print.check_itemscale()`, where we have a list of data frames, one data frame per component:

The print() iterates over the list of data frames, adds table captions and footer (including color codes) as attributes of those data frames, and passes the list to `export_table()`.

```r
print.check_itemscale <- function(x, digits = 2, ...) {
  insight::print_color("# Description of (Sub-)Scales\n", "blue")


  cat(insight::export_table(
    lapply(1:length(x), function(i) {
      out <- x[[i]]
      attr(out, "table_caption") <- c(sprintf("Component %i", i), "red")
      attr(out, "table_footer") <- c(sprintf("Mean inter-item-correlation = %.3f  Cronbach's alpha = %.3f",
                                             attributes(out)$item_intercorrelation,
                                             attributes(out)$cronbachs_alpha), "yellow")


      out
    }),
    digits = digits,
    format = "text",
    missing = "<NA>",
    zap_small = TRUE
  ))
}
```

You could do exactly the same for markdown, except that you need to set `format = "markdown"` in the call to `export_table()`. So, to summarize `export_table()` is now much more flexible, can print table captions/footer (in color) for console output as well, and accepts lists of data frame (the latter we often have for `model_parameters()` / `describe_posterior()` when we have Bayesian models with multiple components).

However, sometimes the preparation for console or markdown output may differ, so we still have different "preparation code" in `print_to_console()` and `print_to_markdown()` (or however these will be called). We cannot include these exceptions in `export_table()`, I guess. But I don't think this is a problem, because `format_table()` and `export_table()` already do a lot of work to prepare printing, if there are any needs left, users may write their own short print-function to add individual stuff.

**Comment by strengejacke** [comment]
@DominiqueMakowski @IndrajeetPatil Any final opinion / decision on the API-design of this feature? To summarize, what I would suggest for now, since we need some updates for the transition (function renaming etc.)

1. _insight_: `format_table()` now has an alias `export_table()`. I started renaming this function call in other packages already.
2. `parameters_table()` is now in _insight_ (and for compatibility, re-exported in _parameters_). This function will be renamed to `format_table()`, and then the "old" `format_table()` is only  `export_table()`.
3. At the moment, we have a `to_table(format = "xy")` function, with alias `tabe_to_markdown()` that simply calls `to_table(format = "markdown")`. **This is something we may have now, but possibly rename in the future, or add aliases!**
4. `print()`, if possible, can be revised and refactored in a way that Dom described above: `print_to_md()` or `print_to_console()`, that call `format_table()` (currently named `parameters_table()` and `export_table()` and do some minor preparation that is required for print. `print()` then calls `print_to_console()`.

Something like that?

**Comment by DominiqueMakowski** [comment]
> But still I like the to_table(), because it is quite clear what it does

Well I understand why you say yes, and I partly agree, but on the other hand it's true that in this context a table is actually quite vague, it could refer to a class table (cf. the discussion in `report`'s API in which we decided to avoid as.table (quiteclose to `to_table`) because of its "reserved" nature for table class), a dataframe (for instance I often refer to dataframes as tables, i.e., a 2x2 matrix), or an exported table (whether in the console or MD). So it's not as clear as what its output will be IMO

> I'd vote for export_table(), with a format argument, and then methods like print_to_md() call export_table(format = "md")

Sounds alright.


> API-design of this feature?

Looks good. Can you make a demo of how to implement a pretty printing for console and MD for a following object using the new API?: 

```r
object <- data.frame(Parameter = c("A", "B", "C"),
                     C_1 = c(1, 3, 5),
                     C_2 = c("X1", "X1", "X2"))

attr(object, "pretty_names") <- c("nice A", "nice B", "nice C")
attr(object, "pretty_cols") <- c("Parameter", "Column 1", "Column 2")
class(object) <- c("newClass", class(object))
```
thanks master 😁 🙏

**Comment by strengejacke** [comment]
Here's an Example:
[test.docx](https://github.com/easystats/insight/files/5577607/test.docx)
[test.pdf](https://github.com/easystats/insight/files/5577608/test.pdf)

**Comment by strengejacke** [comment]
There might be cases where printing to markdown and printing to console only slightly differ. In the above example with printing PCA, both method for md and console are "identical", and in the preparation only this code chunk needs to distinguish between the formats:

https://github.com/easystats/parameters/blob/1fc824f4707d0d1a27935db0b78786fcc5640132/R/utils_pca_efa.R#L173-L186

```r
  # table caption
  if (is.null(rotation_name) || rotation_name == "none") {
    if (format == "markdown") {
      table_caption <- sprintf("Loadings from %s (no rotation)", method)
    } else {
      table_caption <- c(sprintf("# Loadings from %s (no rotation)", method), "blue")
    }
  } else {
    if (format == "markdown") {
      table_caption <- sprintf("Rotated loadings from %s (%s-rotation)", method, rotation_name)
    } else {
      table_caption <- c(sprintf("# Rotated loadings from %s (%s-rotation)", method, rotation_name), "blue")
    }
  }
```

**Comment by strengejacke** [comment]
Another example would be your implementation of `format.easycormatrix()`:

```r
print.easycormatrix <- function(x, digits = 2, stars = TRUE, ...) {
  cat(insight::export_table(format(x, digits = digits, stars = stars)))
  invisible(x)
}
```

```r
to_table.easycormatrix <- function(x, format = "markdown", digits = 2, stars = TRUE, ...) {
  table_caption <- attributes(x)$method
  if (!is.null(table_caption)) {
    table_caption <- paste0("Correlation Matrix (", table_caption, "-method)")
  }
  insight::export_table(format(x, digits = digits, stars = stars), format = format, caption = table_caption, align = "firstleft")
}
```

I'm not sure what kind of "demo" you had in mind? There are some functions that can be refactored, especially now since `export_table()` accepts lists of data frames. Thus, the printing for model_parameters() with different components can now be easily refactored. Maybe this function: https://github.com/easystats/parameters/blob/5573982e47ed051413655c2dfb5fd806e7c33d0e/R/print.parameters_model.R#L212 can be refactored into a `format.parameters_model()`, and then `print.parameters_model()` would look similar to the above implementation in the correlation package.

**Comment by strengejacke** [comment]
So for the first implementation, we may rename `to_table()` into something like `print_to_markdown()`?

**Comment by DominiqueMakowski** [comment]
> so for the first implementation, we may rename to_table() into something like print_to_markdown()?

Or `print_to_md` or `print_md`? Or, we could have a generic `display(x, format="md")`?

**Comment by strengejacke** [comment]
`print_md()` is short, and maybe `display()` as alias.

**Comment by strengejacke** [comment]
Ok, I have a "demo" for _parameters_, I hope that package is still working...  ^^ 

1. `print()` (https://github.com/easystats/parameters/blob/3992da47306c42339afcc7a394e3d96a6a2d99fb/R/print.parameters_model.R#L143), besides some messages that are printed as well, mainly calls `format()` and `export_table()` (lines 155/156)

2. `format()` (https://github.com/easystats/parameters/blob/master/R/format.parameters_model.R) does the general formatting, so you get a nicely formatted data frame (including attributes), or a list of data frames for each component of a model (fixed, random, zero-inflated...)

3. `print_md()` is the equivalent to `print()`, but exports to markdown format. If you look at the code, it's fairly similar (https://github.com/easystats/parameters/blob/3992da47306c42339afcc7a394e3d96a6a2d99fb/R/print_md.R#L3), except that you don't have all the messages displayed via `message()`. It also calls `format()` and `export_table()`, with the argument `format = "markdown"`.

4. `display()` just calls `print_md()` (https://github.com/easystats/parameters/blob/master/R/display.R). `format = "markdown"` is the current default, and currently ignored, since we have no other formats currently. But may be extended, to call `print_html()` etc.


The same for Stan-models:

`print.parameters_stan()` (https://github.com/easystats/parameters/blob/3992da47306c42339afcc7a394e3d96a6a2d99fb/R/print.parameters_model.R#L284) and `print_md.parameters_stan()` (https://github.com/easystats/parameters/blob/3992da47306c42339afcc7a394e3d96a6a2d99fb/R/print_md.R#L35) both do similar things, again `print()` additionally optionally prints some messages, but the workhorse for both functions are `format.parameters_stan()` (https://github.com/easystats/parameters/blob/master/R/format.parameters_stan.R) and `export_table()`.

**Comment by strengejacke** [comment]
so, cleaned summary:

`print()` and `print_md()` both call `format()` and `insight::export_table()`. inside `format()`, `insight::parameters_table()` is called when required.

**Comment by IndrajeetPatil** [comment]
Sorry for the late response, Daniel.

I haven't really had a time to play around with these functions and I personally don't use tables a lot in my workflow, so I don't have much to add to this discussion. But, based on the demos posted in the comments above and example on the website, all of this looks good to me.

**Comment by IndrajeetPatil** [comment]
Only one issue I noticed in the examples was the following:

![image](https://user-images.githubusercontent.com/11330453/99886404-8373db00-2c3c-11eb-887e-acf817f835ea.png)

**Comment by strengejacke** [comment]
Thanks! After releasing _insight_, I have to thoroughly check the examples and vignettes, there might be some stuff I missed. It was really a large refactoring, both in _insight_ and now in _parameters_.

**Comment by IndrajeetPatil** [comment]
Are you still considering mid-December releases?
I was wondering if it is possible to prepone the next cycle to the end of November for two reasons:
1. a lot of new functionality has already been added since the last releases
2. I can then do my own package release cycle in the first week of December and can enjoy Christmas vacation in peace :D

**Comment by strengejacke** [comment]
_insight_ earliest next week, _parameters_ earliest one week later. Depends on when we finally decided on the functions names we're discussing here.

**Comment by DominiqueMakowski** [comment]
Yeah, looks good, good job!. I'll give it a go and will start using it next week ☺️

**Comment by strengejacke** [comment]
I have tweaked `insight::print_parameters()` a bit. Now whenever we have a model-object and another data frame (like `hdi()`, `model_parameters()`, `describe_posterior()`, `p_map()` etc.), and we don't need some extremely funky formatting, it's quite easy now to do the print:

``` r
library(insight)
library(parameters)
data(iris)
iris$Petlen <- cut(iris$Petal.Length, breaks = c(0, 3, 7))
model <- lm(Sepal.Width ~ poly(Sepal.Length, 2) + Species + Petlen, data = iris)

## This is what we want to print
mp <- parameters::model_parameters(model, component = "all", effects = "all")

## this is what would go into "format()"
l <- print_parameters(model, mp, keep_parameter_column = FALSE)
add_attr <- attributes(l)$additional_attributes
x <- lapply(l, function(i) {
  a <- attributes(i)
  attributes(i) <- modifyList(add_attr, attributes(i))
  out <- parameters_table(i)
  i$Group <- NULL
  attributes(out) <- modifyList(a, attributes(out))
  out
})

## This is the final print
cat(export_table(x))
#> # Fixed effects 
#> 
#> Parameter                 | Coefficient |   SE |         95% CI | t(144) |      p
#> ---------------------------------------------------------------------------------
#> (Intercept)               |        3.81 | 0.06 | [ 3.70,  3.93] |  65.50 | < .001
#> Sepal.Length [1st degree] |        4.06 | 0.47 | [ 3.14,  4.98] |   8.70 | < .001
#> Sepal.Length [2nd degree] |       -1.30 | 0.31 | [-1.92, -0.68] |  -4.14 | < .001
#> Species [versicolor]      |       -1.01 | 0.28 | [-1.56, -0.46] |  -3.62 | < .001
#> Species [virginica]       |       -0.99 | 0.29 | [-1.55, -0.43] |  -3.48 | < .001
#> Petlen [4-7]              |       -0.14 | 0.28 | [-0.69,  0.42] |  -0.48 | 0.630



model <- download_model("brms_zi_2")

## This is what we want to print
mp <- parameters::model_parameters(model, component = "all", effects = "all")

## this is what would go into "format()"
l <- print_parameters(model, mp, keep_parameter_column = FALSE)
add_attr <- attributes(l)$additional_attributes
x <- lapply(l, function(i) {
  a <- attributes(i)
  attributes(i) <- modifyList(add_attr, attributes(i))
  out <- parameters_table(i)
  i$Group <- NULL
  attributes(out) <- modifyList(a, attributes(out))
  out
})

## print...
cat(export_table(x))
#> # Fixed effects (conditional) 
#> 
#> Parameter   | Group | Median |         89% CI |     pd | % in ROPE |  Rhat |     ESS
#> ------------------------------------------------------------------------------------
#> (Intercept) |       |  -0.86 | [-1.37, -0.34] | 98.22% |     1.30% | 1.002 | 1003.18
#> persons     |       |   0.84 | [ 0.68,  1.01] |   100% |        0% | 1.002 |  878.17
#> child       |       |  -1.15 | [-1.29, -1.00] |   100% |        0% | 1.001 | 2166.11
#> camper      |       |   0.73 | [ 0.58,  0.89] |   100% |        0% | 1.000 | 3528.44
#> 
#> # Fixed effects (zero-inflated) 
#> 
#> Parameter   | Group | Median |         89% CI |     pd | % in ROPE |  Rhat |     ESS
#> ------------------------------------------------------------------------------------
#> (Intercept) |       |  -0.65 | [-1.82,  0.47] | 83.17% |     7.80% | 1.000 | 1174.50
#> child       |       |   1.86 | [ 1.37,  2.42] |   100% |        0% | 1.002 | 3021.98
#> camper      |       |  -0.84 | [-1.40, -0.24] | 98.95% |     1.68% | 1.000 | 3410.09
#> 
#> # Random effects (conditional) SD/Cor: persons
#> 
#> Parameter   |           Group | Median |       89% CI |   pd | % in ROPE |  Rhat |    ESS
#> -----------------------------------------------------------------------------------------
#> (Intercept) | SD/Cor: persons |   0.12 | [0.00, 0.39] | 100% |    45.27% | 1.005 | 818.82
#> 
#> # Random effects (zero-inflated) SD/Cor: persons
#> 
#> Parameter   |           Group | Median |       89% CI |   pd | % in ROPE |  Rhat |     ESS
#> ------------------------------------------------------------------------------------------
#> (Intercept) | SD/Cor: persons |   1.32 | [0.48, 2.49] | 100% |        0% | 1.004 | 1330.73
```

<sup>Created on 2020-11-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
So, even `format()` could be standardized and similar in many cases, unless we want some special printing...

**Comment by strengejacke** [comment]
Ok, closing this now. A final "demo" with _performance_

1. [`format()`](https://github.com/easystats/performance/blob/master/R/format.R) returns a "pretty data frame" (but no prepared "string" for printing). It usually does some fancy renaming etc., including a possible call to `insight::parameters_table()` (which will be renamed into `insight::format_table()` soon)

2. [`display()`](https://github.com/easystats/performance/blob/master/R/display.R) simply calls other print-methods that console-printing. Used to print to markdown, html, latex, ... Currently, markdown is supported only.

3. [`print()`](https://github.com/easystats/performance/blob/master/R/print-methods.R) usually includes two to four steps: 1) prepare header for output/table, 2) call to `format()`, 3) prepare footer for output/table, 4) call to `export_table(format = "text")`. Steps 1) and 3) can be directly passed as arguments in `export_table()`.

4. [`print_md()`](https://github.com/easystats/performance/blob/master/R/print_md.R) usually includes four steps: 1) header for output/table, 2) call to `format()`, 3) footer for output/table, 4) call to `export_table(format = "markdown")`. Again, steps 1) and 3) can be directly passed as arguments in `export_table()`.

That's our current API. I've added a lot new functionality, mostly for "internal" use, to `insight::parameters_table()`, `insight::print_parameters()` and `insight::export_table()` (former `insight::format_table()`, but this alias will be removed and `insight::parameters_table()` renamed to `insight::format_table()`).

**Comment by DominiqueMakowski** [comment]
Looks great!!
