### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#3]
what about the hexsticker with an image representing some kind of unruly monster (with written "model" on it) that is "opened" by a knight or a weapon or something (with written "insight") on it? Or is this metaphor too far-fetched haha?

**Comment by DominiqueMakowski** [comment]
xray is a good idea! I'll see what I can do. Where is the best place to put visual-related files? In `/Man/...`?

**Comment by strengejacke** [comment]
Yes, I think it's `/man/figures/`.

**Comment by DominiqueMakowski** [comment]
I combined the monster and the Xray, tell me what you think

**Comment by strengejacke** [comment]
That looks great! Some thoughts:

- decrease border size
- slightly decrease font-size and move text upwards some pixel, so you can probably increase the monster, so the xray is better visible
- maybe make the background of the xray darker, so it looks like a "classical" xray (which have a black / dark grey background)

I like this logo, especially since it's something uncommon...

**Comment by strengejacke** [comment]
Do you have the monster-logo w/o xray-overlay? (I mean this one here: https://github.com/easystats/insight/blob/dev/man/figures/monster.png)

Could use that for the presentation...

**Comment by DominiqueMakowski** [comment]
Updated the logo and added the monster w/o x-ray. What about the colour scheme?
