### ISSUE TITLE
testing `model_info()` for rstanarm for different model families

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#375]
I fixed an issue with `model_info()` and `stanreg`, which then broke `model_info()` and `stan_polr()` (which now is on CRAN :-/

So we should check different models and families and see if they work with model_info. Everyone is invited to check one or two functions :-)

- [ ] stan_glm - family xy
- [ ] stan_aov
- [ ] stan_polr
- [ ] stan_betareg
- [ ] stan_biglm
- [ ] stan_clogit
- [ ] stan_gamm4
- [ ] stan_glm.nb
- [ ] stan_glmer
- [ ] stan_glmer.nb
- [ ] stan_lmer
- [ ] stan_lm
- [ ] stan_jm
- [ ] stan_nlmer
- [ ] stan_mvmer

**Comment by IndrajeetPatil** [comment]
Since Daniel has removed tests I had written in https://github.com/easystats/insight/commit/d06cbcc1440c53cbd9a6d962680d91182124d017, we are back to square 1 now on this issue.

**Comment by strengejacke** [comment]
Yes, I still don't like snapshot tests and am not convinced that these reliably detect bugs.

**Comment by bwiernik** [comment]
Could you elaborate on that? The snaps just generate the (long) lists of model information. @IndrajeetPatil did you check that the information in each generated list was correct?

**Comment by IndrajeetPatil** [comment]
> @IndrajeetPatil did you check that the information in each generated list was correct?

To the best of my ability, yes.

But this issue is not just about these particular tests, but more broadly about snapshot tests. The snapshot tests in `parameters` were also removed:
https://github.com/easystats/parameters/commit/fcf31a2836cc9bdc20383affeac91eb43faf86d7

I personally think these tests are actually much stricter than other manual tests we write because we are usually checking only certain parts of the output, while snapshots capture the entire output. So any minute change will also be detected.

Btw, since `vdiffr 1.0`, visual regression tests (being used in `see` package) also use the same strategy.

Relying on them _exclusively_ might be a bad idea, I agree, because they are by default not run on CRAN. But in contexts where generating expected conditions is going to be labor-intensive, they are a lifesaver.

**Comment by strengejacke** [comment]
> Could you elaborate on that?

I looked a bit deeper into snapshot tests. Maybe it depends on the context, and I think there are a few use cases for those tests. In general, I would prefer to test against "original" output. For example, in this case, snapshot tests indeed are easier and save some typing (though `dput()` is not much more effort, and allows testing on CRAN), but like in _parameters_ (https://github.com/easystats/parameters/commit/fcf31a2836cc9bdc20383affeac91eb43faf86d7), I would rather test against something what the original packages return via `summary()` or `coef()`. `model_parameters()` might *work*, but probably not correct, and this is not captured by snapshot tests.

So, reverting the removal in insight, but for parameters, I would suggest better validated tests (though, honestly, I haven't done this consequently in the past by myself). One example would be:

https://github.com/easystats/parameters/blob/fcf31a2836cc9bdc20383affeac91eb43faf86d7/tests/testthat/test-model_parameters_robust.R#L10-L15

Where output is tested explicitly against the results returned by the _sandwich_ package.
