### ISSUE TITLE
Not sure if .variance_distributional is working for logit link function?

### ISSUE THREAD

**Issue by lukestrickland** [easystats/insight#512]
I notice that .variance_distributional sets mu to exp(null_fixef) before using mu in its cvsquared calculation. That makes sense to me for the log link function (exponentiating the intercept of the null model to get an estimate of mu), but is that the correct way to get mu for the logit link function? In that case wouldn't exp(intercept) be odds rather than mu? 

This has drawn my attention because insight:::.variance_family_beta will return a negative number if mu>1, which seems to mean any positive intercept would result in negative variance_family_beta ?

Sorry if I'm totally on the wrong track here (which is possible)

**Comment by strengejacke** [comment]
The related function starts here:
https://github.com/easystats/insight/blob/15f1091b36f866490b9279972aedb3482c152af7/R/compute_variances.R#L590

Tagging @bbolker, who - if I recall right - wrote a function to comute R2 based on the approach from Nakagawa et al. in a GitHub gist (which was, in turn, the base for the implementation in `insight::get_variance()`).

**Comment by strengejacke** [comment]
Do you have a reproducible example? In #883, we validated outputs against *MuMIn*, and results are in line.

**Comment by bbolker** [comment]
I didn't write these functions myself - I cobbled them together from some combination of what was in Jon Lefcheck's `piecewiseSEM` package and Kamil Bartoń's `MuMIn` package (it's hard to reconstruct exactly what, since both of these packages have changed since and I don't feel like doing the archeology).

I find this code: https://github.com/easystats/insight/blob/main/R/compute_variances.R#L635-L644 a little surprising:

I have no idea what's upstream of this, but I would have naturally done something like this:
```
if (is.null(faminfo$family)) {
    mu <- exp(mu)
  } else {
    # transform mu
    linkinv <- make.link(faminfo$link_function)$linkinv
    mu <- linkinv(mu)
  }
```

(I see that `faminfo` has a whole pile of `is_probit`, `is_logit`, etc etc, but the most robust/general way to do this is based on the inverse-link function as generated by `make.link()` ... e.g. what about a model with a `cloglog` link?)

Assuming a log link by default also seems a bit odd, but I guess if we're already inside a piece of code that assumes we're looking at a GLMM this isn't crazy ... ?

**Comment by strengejacke** [comment]
@bbolker Sorry, the question regarding the reprex was not for you :-)
The revised version of `get_variance()` is in #883. The code you mentioned now looks:

https://github.com/easystats/insight/blob/64b89df7832e384430339959f0137523a680bc6a/R/compute_variances.R#L687-L701

This returns results in line with the MuMIn package. I'm not sure `linkinv()` will in general work, at least it's not what MuMIn does. That doesn't mean that MuMIn is doing it right, of course. We may investigate further.

I added _many_ tests to validate results (https://github.com/easystats/insight/blob/64b89df7832e384430339959f0137523a680bc6a/tests/testthat/test-r2_nakagawa_MuMIn.R).

**Comment by bbolker** [comment]
I see that `MuMIn` has a comment (lines 119-120) of `R/r.squaredGLMM2.R` that says

```
# XXX: inverse-link seems to give more reasonable value for non-logit
                # links, should inv-logit (plogis) be used here always?
```

I can't figure out the source of the `mu` transformations here (they're not simple applications of the inverse-link function to the mean of the fixed effects, AFAICT, and at a quick skim I don't see anything like them in the Nakagawa/Schielzeth/Johnson paper, nor in the help page).  Maybe we can ask Kamil Bartoń for more info ... ?

**Comment by strengejacke** [comment]
I found something in the supplemental (https://royalsocietypublishing.org/doi/suppl/10.1098/rsif.2017.0213). I'll try to see if I can reproduce those results.
