### ISSUE TITLE
Important: `get_predicted.default` needs default value for `predict` argument

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#547]
Otherwise, any call like `get_predicted(model)` will generate an error.

The default should be `predict = "expectation"`

https://github.com/easystats/insight/blob/master/R/get_predicted.R#L167

**Comment by strengejacke** [comment]
hm, probably too late for the current update.

**Comment by strengejacke** [comment]
Should be resolved in #549 
Note, however, that `get_predicted(x, type = "response")` will fail, because `predict` is not set to `NULL` now any longer. So whenever you pass `type` to the default method, you must explicitly set `predict = NULL`. The intention not to use a default value was that you instead need to explicitly set either `predict` or `type`, which I found less confusing...

**Comment by bwiernik** [comment]
Can we make it so that if both are present, `type` overrides `predict`?

**Comment by strengejacke** [comment]
Yes, I think so. I'm not sure why we decided to error when both are given...

**Comment by bwiernik** [comment]
> Can we make it so that if both are present, type overrides predict?

@strengejacke Did the above change get implemented?

**Comment by strengejacke** [comment]
Yes, but just after CRAN submission. So it's only in the version on R Universe
