### ISSUE TITLE
Move `get_statistic()` to `parameters`?

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/insight#617]
I was surprised to learn that this function was in `insight`. Would it make sense to move it to `parameters`?

I don't see a lot of call to that function internally in `insight`. Anyone knows if it is used in another package that does not import `parameters`?

**Comment by strengejacke** [comment]
No, but the general idea was to have all access functions that look "insight" models are in this package. The ultimate goal would be that _insight_ allows to access all information, and there's only _one_ `model_parameters()` that just calls insight-functions.

**Comment by vincentarelbundock** [comment]
sorry, do you mean "no we should not move it to parameters", or "no it is not called by other functions"?

Are you implying that `standard_errors()`, `p_value()`  et al. should all go in `insight` eventually?

**Comment by bwiernik** [comment]
I'm guessing meant that he didn't know if other packages used this function. 

I guess I see get_statistic() as analogous to get_parameters(). They are simple functions to quickly extract a part of the model. They don't do any of the more complex computations that model_parameters(), standard_error(), or p_value() do.   Could those two probably live in {parameters} instead of {insight}, yeah, but all of the other simple get_*() functions live in {insight}, so there is also value in maintaining that consistency IMO

**Comment by vincentarelbundock** [comment]
Sounds reasonable. Thanks!
