### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by strengejacke** [easystats/insight#63]
This test ( 1. Error: get_variance (@test-glmmTMB.R#255) ) and maybe the others that call `get_variance()` currently fail.

Reason: To compute variances, I use `update(model)` somewhere in the `get_variance()` function, which in turn calls `eval(call, parent.frame())`, which in turn does not find the data from `call`. Error: `object 'fish' not found`.

We probably need to push `fish` (the data frame) in the test environment, i.e. somewhere in "test-glmmTMB.R" we need to make to data "globally" available. Any ideas how to do this?

Else, all milestones for the next release are done.

**Comment by DominiqueMakowski** [comment]
This is a problem of in-model data storage, which I believed it is due to a design decision of glmmTMB, which decided not directly storing data in their model object. Fortunately, in R, there is the powerful workaround with `parent.frame` that can work, but if the model is too deeply encapsulated in a function, or saved and retrieved through download, it would eventually fail.

I am not sure if there is a trick of addressing this in R, 

However, in general, this reminds me of Julia when I wanted to implement something that relied on an `update()` method, which Julia doesn't have (see [issue](https://github.com/JuliaStats/StatsModels.jl/issues/73)). It appeared that there was a consensus about the worthlessness of storing the original dataframe in the fitted object (apparently not useful enough, too heavy and so on...).

Anyway, one workaround for the Julia package was to add the possibility of adding the original data to the functions. Something like `report(model, data=df)`. Altough possibly very rarely used, we could eventually add a data argument, set to NULL by default. In the vast majority of cases, we wouldn't need it as we are able to retrieve the data. However, in the very few cases where basically `get_data()` would error, we could throw a warning asking the user to provide a data argument. This data could be passed down (through the `...`) down to the `update()` method. If `data` is provided, `update()` uses it, otherwise, it attempts to retrieve it through `get_data()`. 

But it's a lot of fuss for a few edgecases...

**Comment by strengejacke** [comment]
I think the problem is that `update()` has no argument to supply some data. An additional argument won't help. Everything works fine, except when testing `get_variance()`

**Comment by strengejacke** [comment]
For glmmTMB, we load the fish-data from the internet. For all other models, we use `data()` in the tests, so I think these work. I'll comment out all failing tests for now...

**Comment by DominiqueMakowski** [comment]
Well in fact `update()` can take any argument that the original model takes:

```r
model <- lm(Sepal.Length ~ Species, data=iris)
update(model, data=dplyr::filter(iris, Species!="Setosa"))
```
```
Call:
lm(formula = Sepal.Length ~ Species, data = dplyr::filter(iris, 
    Species != "Setosa"))

Coefficients:
      (Intercept)  Speciesversicolor   Speciesvirginica  
            5.006              0.930              1.582 
```

But again, the "optional data argument" proposal would be *very* rarely used, so we can stick to our current beahaviour for now. Good that you've managed to find a workaround :)
