### ISSUE TITLE
format_bf() should also add stars for lower BFs

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#954]
We should also add stars for the BF01 (i.e., < 1/3, 1/10 etc.)
``` r
insight::format_bf(11, stars=T)
#> [1] "BF = 11.00**"
insight::format_bf(0.09, stars=T)
#> [1] "BF = 0.090"
```

<sup>Created on 2024-11-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
I think the rationale was to indicate superiority onlk, not inferiority. @mattansb WDYT?

**Comment by mattansb** [comment]
Since start denote significant results in NHST = a difference/effect, having them also mark strong evidence for the opposite of that might be confusing/misleading.

Also, if setting `stars_only = TRUE` we would get this absurd result:

```R
insight::format_bf(c(0.09, 11), stars = TRUE, stars_only = TRUE)
#> [1] "**"   "**"
```

A solution could be to use a different symbol for evidence _against_. I've seen ° (`"\u00B0"`) used. What do you think?

```R
insight::format_bf(c(0.09, 11), stars = TRUE)
#> [1] "BF = 0.090°°"   "BF = 11.00**"
```

Or any other symbol (other than +/†/*), like ⁑, ⩮ (which is cool - is "significantly" equal!)

**Comment by bwiernik** [comment]
I like ° ("\u00B0")

**Comment by strengejacke** [comment]
Should we add that symbol _by default_, or explicitly via an argument? We now have an argumen `inferiority_star`, which can be used to set that symbol. If `NULL`, no symbol is added. What should be the default?

``` r
library(insight)
bfs <- c(0.000045, 0.233, NA, 1557, 3.54)
format_bf(bfs)
#> [1] "BF < 0.001" "BF = 0.233" ""           "BF > 1000"  "BF = 3.54"
format_bf(bfs, stars = TRUE)
#> [1] "BF < 0.001°°°" "BF = 0.233°"   ""              "BF > 1000***" 
#> [5] "BF = 3.54*"
format_bf(bfs, stars = TRUE, inferiority_star = "§")
#> [1] "BF < 0.001§§§" "BF = 0.233§"   ""              "BF > 1000***" 
#> [5] "BF = 3.54*"
```

<sup>Created on 2024-11-06 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
I like the degree symbol that Mattan recommended as a default

**Comment by mattansb** [comment]
Looks good @strengejacke - thanks!
